// Barrel file for components/. Auto-maintained: exports every top-level
// component so consumers can import from '@/components' instead of deep paths.
export { default as AnalyticsProvider } from './AnalyticsProvider';
export { default as AttendeeTable, truncateStellarKey } from './AttendeeTable';
export { default as CategoryCard } from './CategoryCard';
export { default as ChatWidget } from './ChatWidget';
export { default as DateTimePicker } from './DateTimePicker';
export { EmailCampaignCard } from './EmailCampaignCard';
export { EmailCampaignComposer } from './EmailCampaignComposer';
export { EscrowBalanceCard } from './EscrowBalanceCard';
export { default as EventPreviewOverlay } from './EventPreviewOverlay';
export { default as FeaturedEvents } from './FeaturedEvents';
export { default as Footer } from './Footer';
export { default as MobileDrawer } from './MobileDrawer';
export { default as Navbar } from './Navbar';
export { NetworkMismatchBanner } from './NetworkMismatchBanner';
export { NetworkSwitcher } from './NetworkSwitcher';
export { default as PaymentFlow } from './PaymentFlow';
export { default as PaymentTimeline } from './PaymentTimeline';
export { default as QRModal } from './QRModal';
export { RevenueChart } from './RevenueChart';
export { SponsorTierCard } from './SponsorTierCard';
export { default as SponsorTierPreview } from './SponsorTierPreview';
export { default as StellarPayment } from './StellarPayment';
export { default as TaxBreakdown } from './TaxBreakdown';
export { default as ThemeToggle } from './ThemeToggle';
export { default as TicketCard } from './TicketCard';
export { default as Toast } from './Toast';
export { default as TransactionStatus } from './TransactionStatus';
export { TransactionSummaryModal } from './TransactionSummaryModal';
export { default as VenueMap } from './VenueMap';
export { WalletButton } from './WalletButton';
export { WalletConnect } from './WalletConnect';
export { WalletInfo } from './WalletInfo';
export { default as WalletInstallPrompt } from './WalletInstallPrompt';
export { default as WalletLinkSection } from './WalletLinkSection';
